// <auto-generated />
using System;
using Liga305.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Liga305.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Liga305DbContext))]
    [Migration("20260417163927_DomainModel")]
    partial class DomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Liga305.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BotSteamName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DotaMatchId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LobbyName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LobbyPassword")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool?>("RadiantWin")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DotaMatchId");

                    b.HasIndex("SeasonId", "Status");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.MatchPlayer", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Abandoned")
                        .HasColumnType("boolean");

                    b.Property<bool>("JoinedLobby")
                        .HasColumnType("boolean");

                    b.Property<double?>("MmrAfter")
                        .HasColumnType("double precision");

                    b.Property<double>("MmrBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("RdAfter")
                        .HasColumnType("double precision");

                    b.Property<double>("RdBefore")
                        .HasColumnType("double precision");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("MatchId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.MmrHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Delta")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<double>("MmrAfter")
                        .HasColumnType("double precision");

                    b.Property<double>("MmrBefore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId", "SeasonId", "CreatedAt");

                    b.ToTable("MmrHistory");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonId", "Status", "EnqueuedAt");

                    b.HasIndex("SeasonId", "UserId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Queued'");

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("StartingMmr")
                        .HasColumnType("double precision");

                    b.Property<double>("StartingRd")
                        .HasColumnType("double precision");

                    b.Property<double>("StartingVolatility")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.SeasonPlayer", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Abandons")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<double>("Mmr")
                        .HasColumnType("double precision");

                    b.Property<double>("Rd")
                        .HasColumnType("double precision");

                    b.Property<double>("Volatility")
                        .HasColumnType("double precision");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonId", "Mmr");

                    b.ToTable("SeasonPlayers");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("SteamId64")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SteamId64")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.Match", b =>
                {
                    b.HasOne("Liga305.Domain.Entities.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.MatchPlayer", b =>
                {
                    b.HasOne("Liga305.Domain.Entities.Match", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liga305.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.MmrHistory", b =>
                {
                    b.HasOne("Liga305.Domain.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liga305.Domain.Entities.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liga305.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liga305.Domain.Entities.QueueEntry", b =>
                {
                    b.HasOne("Liga305.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Liga305.Domain.Entities.Season", "Season")
                        .WithMany("QueueEntries")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liga305.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.SeasonPlayer", b =>
                {
                    b.HasOne("Liga305.Domain.Entities.Season", "Season")
                        .WithMany("Players")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liga305.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.Match", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Liga305.Domain.Entities.Season", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Players");

                    b.Navigation("QueueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
